### PR TITLE
Rigid body physics

### PR DESCRIPTION
**Pull request by Rhuagh**
This change is [Reviewable](https://reviewable.io/reviews/rhuagh/rhusics/36)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
:tada: this is awesome!  Thanks!

**Comment by isurakka** [comment]
Would it be possible split the solver systems in such a way that you could use the current frame physics state for rendering (another system) while the state for next is being calculated?

**Comment by dkushner** [comment]
Reviewed 1 of 16 files at r1, 30 of 31 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Cargo.toml, line 22 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UQ6sQa4TYT7hgrdds:-L1UQ6sQa4TYT7hgrddt:b-9ii92x) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/Cargo.toml#L22)):*
> ```TOML
> [dependencies]
> cgmath = "0.15"
> collision = { git = "https://github.com/kvark/collision-rs/" }
> ```

Is there a pending release to collision-rs we should wait for? 

---

*[src/ecs/physics/prelude2d.rs, line 43 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UYPjmlrh9CYZzvvkP:-L1UYPjmlrh9CYZzvvkQ:bo2demy) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/ecs/physics/prelude2d.rs#L43)):*
> ```Rust
> 
> /// Register required components and resources in world
> pub fn world_physics_register_with_spatial<Y>(world: &mut World)
> ```

Can the name of the helper registration functions be changed to clarify their purpose for the end user? 

---

*[src/ecs/physics/systems/impulse_solver.rs, line 83 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UYBbqE-ZhPUlJx08H:-L1UYBbqE-ZhPUlJx08I:bjogd4f) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/ecs/physics/systems/impulse_solver.rs#L83)):*
> ```Rust
> /// - `O`: Internal type used for abstracting over cross products in 2D/3D,
> ///        usually `Scalar` or `Vector3`
> pub struct ContactResolutionSystem<P, R, I, A, O>
> ```

Should this and the `NextFrameSetupSystem` be separated out into another module/file?

---

*[src/physics/util.rs, line 6 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1Ua9_0yjhYerFpqpjR:-L1Ua9_0yjhYerFpqpjS:b2i6sct) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/physics/util.rs#L6)):*
> ```Rust
> 
> /// Cross product abstraction
> pub trait Cross<RHS = Self> {
> ```

Name may be confusing when associated with mathematical types since its not a "true" cross product. I definitely get the requirement to unify an R^3 cross product with the R^2 analog but just calling this out. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36)*

**Comment by Rhuagh** [comment]
Reviewed 9 of 16 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Cargo.toml, line 22 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UQ6sQa4TYT7hgrdds:-L1UcmGjkL4sy5gvwYEW:blps87l) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/Cargo.toml#L22)):*
<details><summary><i>Previously, dkushner (Dave Kushner) wrote…</i></summary><blockquote>

Is there a pending release to collision-rs we should wait for? 
</blockquote></details>

Na, we can do that fix before we release

---

*[src/ecs/physics/prelude2d.rs, line 43 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UYPjmlrh9CYZzvvkP:-L1Uc7PXRT_tdgIcSdTd:bg0jaui) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/ecs/physics/prelude2d.rs#L43)):*
<details><summary><i>Previously, dkushner (Dave Kushner) wrote…</i></summary><blockquote>

Can the name of the helper registration functions be changed to clarify their purpose for the end user? 
</blockquote></details>

Possibly, I just dont know to what.

---

*[src/ecs/physics/systems/impulse_solver.rs, line 83 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UYBbqE-ZhPUlJx08H:-L1UcKMCnSgrJpCZeM3W:b-l95due) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/ecs/physics/systems/impulse_solver.rs#L83)):*
<details><summary><i>Previously, dkushner (Dave Kushner) wrote…</i></summary><blockquote>

Should this and the `NextFrameSetupSystem` be separated out into another module/file?
</blockquote></details>

Possibly

---

*[src/physics/util.rs, line 6 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1Ua9_0yjhYerFpqpjR:-L1UcYSbTKfp7TDvdMuU:b-clklse) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/physics/util.rs#L6)):*
<details><summary><i>Previously, dkushner (Dave Kushner) wrote…</i></summary><blockquote>

Name may be confusing when associated with mathematical types since its not a "true" cross product. I definitely get the requirement to unify an R^3 cross product with the R^2 analog but just calling this out. 
</blockquote></details>

Its a partial cross product for 2D, full for 3D. `PartialCross` better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36)*

**Comment by dkushner** [comment]
Reviewed 1 of 31 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ecs/physics/prelude2d.rs, line 43 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UYPjmlrh9CYZzvvkP:-L1Uk5WJFyCg462k8qP5:b-pw9rd) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/ecs/physics/prelude2d.rs#L43)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Possibly, I just dont know to what.
</blockquote></details>

Perhaps change the helpers in the collide preludes to `register_collision` and `register_collision_with_sorting` and then the physics prelude ones to `register_physics` and `register_physics_with_sorting` or something to that effect? Is there any harm in unifying them and registering the sorting components by default?

---

*[src/physics/util.rs, line 6 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1Ua9_0yjhYerFpqpjR:-L1UfFOFcIoehgvMkohX:b-3kvoh8) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/physics/util.rs#L6)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Its a partial cross product for 2D, full for 3D. `PartialCross` better?
</blockquote></details>

Actually, yeah that sounds great and is perfectly in line with things like `PartialEq` where the impl reflects behaviour that resembles the mathematical operation. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36)*

**Comment by dkushner** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-:-L1V875Nf4V4KxDuw8P_:bnfp4nl)*

**Comment by Rhuagh** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Cargo.toml, line 22 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UQ6sQa4TYT7hgrdds:-L1XVx5Ik-7cNOHGUecI:b-h4unc) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/Cargo.toml#L22)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Na, we can do that fix before we release
</blockquote></details>

Will defer this until later, since we want to get this merged.

---

*[src/ecs/physics/prelude2d.rs, line 43 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UYPjmlrh9CYZzvvkP:-L1XXHSSyMURPKW1dUt8:b-d4dmx7) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/ecs/physics/prelude2d.rs#L43)):*
<details><summary><i>Previously, dkushner (Dave Kushner) wrote…</i></summary><blockquote>

Perhaps change the helpers in the collide preludes to `register_collision` and `register_collision_with_sorting` and then the physics prelude ones to `register_physics` and `register_physics_with_sorting` or something to that effect? Is there any harm in unifying them and registering the sorting components by default?
</blockquote></details>

I'm removing the spatial specific version, and just registering the dbvt in the normal collision method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36)*

**Comment by Rhuagh** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/physics/util.rs, line 6 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1Ua9_0yjhYerFpqpjR:-L1XXWGSavDvRLaMzvAz:b-nlp088) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/physics/util.rs#L6)):*
<details><summary><i>Previously, dkushner (Dave Kushner) wrote…</i></summary><blockquote>

Actually, yeah that sounds great and is perfectly in line with things like `PartialEq` where the impl reflects behaviour that resembles the mathematical operation. 
</blockquote></details>

It's actually a real cross product for 2d also, it's just that it's easier to represent a 2d cross product result as a scalar, since the normal will always be parallel to the z axis for two vectors in the xy plane

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36)*

**Comment by Rhuagh** [comment]
Review status: 16 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ecs/physics/systems/impulse_solver.rs, line 83 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UYBbqE-ZhPUlJx08H:-L1X_ONs1u2Ckh34Ad3m:b-896fix) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/ecs/physics/systems/impulse_solver.rs#L83)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

Possibly
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36)*

**Comment by Rhuagh** [comment]
Review status: 16 of 33 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/ecs/physics/prelude2d.rs, line 43 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1UYPjmlrh9CYZzvvkP:-L1X_V9pmEBFHtE_iPYa:b-896fix) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/ecs/physics/prelude2d.rs#L43)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

I'm removing the spatial specific version, and just registering the dbvt in the normal collision method.
</blockquote></details>

Done.

---

*[src/physics/util.rs, line 6 at r3](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-L1Ua9_0yjhYerFpqpjR:-L1X_Rtfr6N_hOviopLO:b-896fix) ([raw file](https://github.com/rhuagh/rhusics/blob/b15c03cbd3bffa107c5b238df411f497c5333f0b/src/physics/util.rs#L6)):*
<details><summary><i>Previously, Rhuagh (Simon Rönnberg) wrote…</i></summary><blockquote>

It's actually a real cross product for 2d also, it's just that it's easier to represent a 2d cross product result as a scalar, since the normal will always be parallel to the z axis for two vectors in the xy plane
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36)*

**Comment by Rhuagh** [comment]
Reviewed 1 of 16 files at r1, 15 of 31 files at r3, 17 of 17 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36)*

**Comment by dkushner** [comment]
:lgtm:

---

Reviewed 6 of 17 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rhuagh/rhusics/36#-:-L1XeNWaf0mrI4ar6ZHp:bnfp4nl)*

**Pull request merged**
